version: '3.8'

services:
  balances-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balances-watcher
    ports:
      - "4000:8080"
    env_file:
      - .env
    restart: unless-stopped
