apiVersion: apps/v1
kind: Deployment
metadata:
  name: balances-watcher
  labels:
    app: balances-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balances-watcher
  template:
    metadata:
      labels:
        app: balances-watcher
    spec:
      containers:
        - name: app
          image: ghcr.io/limitofzero/balances-watcher:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: balances-watcher-secrets
          env:
            - name: RUST_LOG
              value: "${RUST_LOG}"
            - name: HTTP_BIND
              value: "${HTTP_BIND}"
