apiVersion: v1
kind: Service
metadata:
  name: token-balances-watcher
spec:
  selector:
    app: token-balances-watcher
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
